language: ruby
script: 'rake bacon'
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - jruby
  - rbx-2

notifications:
  email:
    - m.fellinger@gmail.com

branches:
  only:
    - master
